language: java
sudo: false
jdk:
  - openjdk7
  - oraclejdk7

before_deploy:
  - mvn appengine:update

deploy:
  provider: gae
  keyfile: gae-secret.json
  project: jtalaveragre-tic-tac-toe
  config: src/main/webapp/WEB-INF/appengine-web.xml
  on:
    jdk: oraclejdk7
cache:
  directories:
  - $HOME/.m2

before_install:
- openssl aes-256-cbc -K $encrypted_662077106e81_key -iv $encrypted_662077106e81_iv
  -in gae-secret.json.enc -out gae-secret.json -d
